### ISSUE TITLE
Enable custom numbering

### ISSUE THREAD

**Issue by Emryn-Hofmann** [gijs-pennings/latex-homework#1]
Feature request: The ability to enable custom numbering, including adding sub-exercises, e.g. 1a, 1ai etc

**Comment by gijs-pennings** [comment]
I was thinking of adding an optional parameter to the `\exercise` command, allowing you to fully customize the 'number part' for each exercise individually (and defaulting to current behavior if not specified). Does that work for you as well? I think that's by far the easiest solution that works in all cases.

I personally don't want to add commands for sub-exercises. Firstly, because I think using something like `\begin{enumerate}[a.]` is much cleaner, and secondly, because I don't know where to draw the line; should I then also add a command for sub-sub-exercises? I prefer to keep it simple.

**Comment by Emryn-Hofmann** [comment]
Ah okay, yeah that works well, and I'd never thought of using enumerate, that'll work well too. Thank you :)
