### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by tathagata-raha** [gijs-pennings/latex-homework#2]
Can you tell me how to change the font size here?

**Comment by gijs-pennings** [comment]
I suppose you mean document-wide, choosing between the standard 10, 11, and 12pt? That's a good question, actually. Without modifying the class itself, there doesn't seem to be an easy way. Otherwise, you can change the font size option at line 22 of the current `homework.cls` (or you can even use a different class altogether, for example from [extsizes](https://ctan.org/pkg/extsizes) or [KOMA-Script](https://ctan.org/pkg/koma-script)). Another option is the [anyfontsize](https://ctan.org/pkg/anyfontsize) package.
